/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fre;
import java.sql.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;

/**
 *
 * @author gaurav
 */
public class entp_log extends javax.swing.JFrame {

    /**
     * Creates new form entp_log
     */
    int id,type,ctr1,ctr2;
    int ct=0;
    double lod;
     Statement st;
    Connection con;
    String url,user,password;
    public entp_log() {
        initComponents();
         try{
			url="jdbc:mysql://localhost:3306/dbproject?autoReconnect=true&useSSL=false";
			 user="root";
			 password="tiger";
			
			 Class.forName("com.mysql.jdbc.Driver");
				
		}
		catch(Exception e){
			System.out.println("Exception in connecting...."+e.getLocalizedMessage());
		}
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b1 = new javax.swing.JButton();
        cb1 = new javax.swing.JComboBox<>();
        jl1 = new javax.swing.JLabel();
        jl2 = new javax.swing.JLabel();
        cb2 = new javax.swing.JComboBox<>();
        jb2 = new javax.swing.JButton();
        jB4 = new javax.swing.JButton();
        jL3 = new javax.swing.JLabel();
        jTF1 = new javax.swing.JTextField();
        jB5 = new javax.swing.JButton();
        jB6 = new javax.swing.JButton();
        jL4 = new javax.swing.JLabel();
        jCB3 = new javax.swing.JComboBox<>();
        jCB4 = new javax.swing.JComboBox<>();
        jB7 = new javax.swing.JButton();
        jL7 = new javax.swing.JLabel();
        jB8 = new javax.swing.JButton();
        jB9 = new javax.swing.JButton();
        jL8 = new javax.swing.JLabel();
        jTF4 = new javax.swing.JTextField();
        jL9 = new javax.swing.JLabel();
        jTF3 = new javax.swing.JTextField();
        jB10 = new javax.swing.JButton();
        jB11 = new javax.swing.JButton();
        scb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        b1.setText("Check duty charges");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        cb1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "India", "South Africa", "Dubai", "Canada","Spain" }));

        jl1.setText("Source");

        jl2.setText("Destination:");

        cb2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "India", "South Africa", "Dubai", "Canada","Spain" }));

        jb2.setText("Go");
        jb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb2ActionPerformed(evt);
            }
        });

        jB4.setText("Validate item info");
        jB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB4ActionPerformed(evt);
            }
        });

        jL3.setText("Enter no. of items: ");

        jTF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF1ActionPerformed(evt);
            }
        });

        jB5.setText("Check");
        jB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB5ActionPerformed(evt);
            }
        });

        jB6.setText("Place order");
        jB6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB6ActionPerformed(evt);
            }
        });

        jL4.setText("Source");

        jCB3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "India", "South Africa", "Dubai", "Canada","Spain" }));

        jCB4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "India", "South Africa", "Dubai", "Canada","Spain" }));

        jB7.setText("Show ships");
        jB7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB7ActionPerformed(evt);
            }
        });

        jL7.setText("Destination:");

        jB8.setText("Track Order");
        jB8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB8ActionPerformed(evt);
            }
        });

        jB9.setText("Cancel Order");
        jB9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB9ActionPerformed(evt);
            }
        });

        jL8.setText("Enter Order_id: ");

        jL9.setText("Enter Ship_id:");

        jB10.setText("Done");
        jB10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB10ActionPerformed(evt);
            }
        });

        jB11.setText("cancel_it");
        jB11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB11ActionPerformed(evt);
            }
        });

        scb.setText("sign_out");
        scb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b1)
                    .addComponent(jB4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jL4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCB3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jL3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jB6)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jl1)
                                    .addGap(31, 31, 31)
                                    .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jL7)
                                .addComponent(jl2))
                            .addGap(33, 33, 33)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jCB4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jB9)
                        .addComponent(jB8)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addComponent(jL9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTF3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jL8)
                                    .addGap(31, 31, 31)
                                    .addComponent(jTF4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(228, 228, 228)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jB10)
                                        .addComponent(jB7)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(126, 126, 126)
                                    .addComponent(jB11))))))
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jB5)
                        .addGap(253, 253, 253))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jb2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(106, 106, 106))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(scb)
                        .addGap(72, 72, 72))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(b1)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl1)
                    .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl2)
                    .addComponent(cb2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jb2)
                .addGap(28, 28, 28)
                .addComponent(jB4)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jL3)
                    .addComponent(jTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jB5)
                        .addGap(25, 25, 25)
                        .addComponent(jB6)
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jL4)
                            .addComponent(jCB3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jL7)))
                    .addComponent(jCB4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(jB7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jL9)
                        .addComponent(jTF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jB10))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jB8)
                        .addGap(18, 18, 18)
                        .addComponent(jB9)
                        .addGap(42, 42, 42)
                        .addComponent(jL8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jB11)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
       jl1.setVisible(false);
       jl2.setVisible(false);
       cb1.setVisible(false);
       cb2.setVisible(false);
       jb2.setVisible(false);
       
       jTF1.setVisible(false);
       jB5.setVisible(false);
       jL3.setVisible(false);
       
       jCB3.setVisible(false);
       jCB4.setVisible(false);
       jL7.setVisible(false);
       jB7.setVisible(false);
       jL4.setVisible(false);
       
       jL8.setVisible(false);
       jTF4.setVisible(false);
       jB11.setVisible(false);
       
       jL9.setVisible(false);
       jTF3.setVisible(false);
       jB10.setVisible(false);
        
    }//GEN-LAST:event_formWindowActivated

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
       jl1.setVisible(true);
       jl2.setVisible(true);
       cb1.setVisible(true);
       cb2.setVisible(true);
       jb2.setVisible(true);
       
       
       
       
       
       
    }//GEN-LAST:event_b1ActionPerformed

    private void jb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb2ActionPerformed
        // TODO add your handling code here:
       //display_dC d=new display_dC();
       
       //d.setVisible(true);
       try{
       con=DriverManager.getConnection(url, user, password);
        st=con.createStatement();
        ResultSet rs;
        
        if(cb1.getSelectedIndex()==cb2.getSelectedIndex())
        {
        JOptionPane.showMessageDialog(this,"Please select diff src & destn");
        return;
        }
        
        rs=st.executeQuery("select * from dc where frm="+(cb1.getSelectedIndex()+1)+
                " and"+" destn="+(cb2.getSelectedIndex()+1));
        rs.next();
        
        String src;
        src=(rs.getDouble(3)+"% "+"per package "+"on perishables")+"\n"+
                (rs.getDouble(4)+"% "+"per machine "+"on electronics")+"\n"+
                (rs.getDouble(5)+"% "+"per vehicle "+"on automobiles");
         JOptionPane.showMessageDialog(this,src);
        
       }
       catch(Exception e){
       System.out.println("In entp_log.java...."+e.getLocalizedMessage());
       }
       // create a function in display_dC and pass selected row info
       // to it.
       
       
        
    }//GEN-LAST:event_jb2ActionPerformed

    private void jB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB5ActionPerformed
        // TODO add your handling code here:
        
        //Display whether shipment possible or not using jDialog Box.....
        
       //Display place order button only if 
       //validity is true...... using if cond'n
        int p;
        boolean bol=true;
	p=Integer.parseInt(jTF1.getText());
        System.out.println(p+" "+type);
	lod=0.0;
	if(type==1)
	lod=p*0.5*0.00110231;
	else if(type==2) 
	lod=p*5*0.00110231;
	else if(type==3) 
	lod=p*1000*0.00110231;
			
	if(lod < 50)
	bol=false; 
        
        if(bol){
        JOptionPane.showMessageDialog(this,"Your order Valid to be placed");
         jB6.setEnabled(true);
        }
        if(!bol){
            String src;
            src="Sorry your order didn't cross a threshold amount "
						+"\n hence can't be placed";
			
	if(type==1)
	src=src+" "+"\nGo for atleast 500 packages";	
	else if(type==2) 
	src=src+" "+"\nGo for atleast 300 machines";	
	else if(type==3)
	src=src+" "+"\nGo for atleast 50 automobiles";
	 JOptionPane.showMessageDialog(this,src);
        jB6.setEnabled(false);
        }
        
    }//GEN-LAST:event_jB5ActionPerformed

    private void jB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB4ActionPerformed
        // TODO add your handling code here:
       jTF1.setVisible(true);
       jB5.setVisible(true);
       jL3.setVisible(true); 
       
    }//GEN-LAST:event_jB4ActionPerformed

    private void jTF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF1ActionPerformed

    private void jB6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB6ActionPerformed
        // TODO add your handling code here:
        jCB3.setVisible(true);
       jCB4.setVisible(true);
       jL7.setVisible(true);
       jB7.setVisible(true);
       jL4.setVisible(true);
       
       jL9.setVisible(true);
       jTF3.setVisible(true);
       jB10.setVisible(true);
    }//GEN-LAST:event_jB6ActionPerformed

    private void jB7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB7ActionPerformed
        // TODO add your handling code here:
        
        //Display Ships with id.... 
        
        try{
           con=DriverManager.getConnection(url, user, password);
	   st=con.createStatement();
		  
	
	
      	  ctr1=jCB3.getSelectedIndex() +1;
          ctr2=jCB4.getSelectedIndex() +1;
      	  
      ResultSet rs=st.executeQuery("select * from Ship,Status where Ship.id=Status.id and type="+type+" and"+
			              " ctr="+ctr1+" and"+" engaged=0 and Maintenance=0 and (destn=Null or "+ ctr2+")");
	String src="<html>";
	while(rs.next()){
	src=src+("Ship id: "+rs.getInt(1)+" Ship_name: "+rs.getString(2)+" Load range b/w "+rs.getInt(5)+"-"+rs.getInt(4)+
	" Cost per miles: "+rs.getInt(8)+" $")+" <br> ";	
	}  
        src=src+" </html>";
         JOptionPane.showMessageDialog(this,src);
         
         st.close();
         con.close();
        }
        catch(Exception e){
            System.out.print("In entp_log.java.... "+e.getLocalizedMessage());
        }
    }//GEN-LAST:event_jB7ActionPerformed

    private void jB8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB8ActionPerformed
        // TODO add your handling code here:
        
        // create a new frame and display details in tabular form
       try{ 
           con=DriverManager.getConnection(url, user, password);
		  st=con.createStatement();
		Statement st1=con.createStatement();
		int shipid,order_id;
                disp_loc obj=new disp_loc();
		  ResultSet rs=st.executeQuery("select order_id,ship_id from serv where cust_id="+id);
                  if(rs.next()==false)
                    JOptionPane.showMessageDialog(this," You haven't shipped anything");
                  else
                  {
 		 ResultSet rs1;
                  while(rs.next()){
                    shipid=rs.getInt(2);
		    order_id=rs.getInt(1); 
		  rs1=st1.executeQuery("select * from uploc where ship_id="+shipid);
		System.out.println(shipid);
		  while(rs1.next()) {
			
                     
                     obj.order_id=order_id;
                     obj.ship_id=shipid;
                     obj.dt=rs1.getDate(5).toString();
                     obj.ti=rs1.getTime(6).toString();
		     obj.near= 	rs1.getString(2);
                     obj.lat=(float)rs1.getDouble(3);
                     obj.logt=(float)rs1.getDouble(4);
			
                     obj.add_row();
		  }   
                  }  
           obj.setVisible(true);
           }
       }
       catch(Exception e){
             System.out.print("In entp_log.java.... "+e.getLocalizedMessage());
       }
        
    }//GEN-LAST:event_jB8ActionPerformed

    private void jB9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB9ActionPerformed
        // TODO add your handling code here:
        
        try{
            con=DriverManager.getConnection(url, user, password);
	   st=con.createStatement();
           ResultSet rs;
           String src="Your current orders"+"\n";
           rs=st.executeQuery("select order_id,lod,ship_id from serv where cust_id="+id);
          
           if(rs.next()==false){
                  JOptionPane.showMessageDialog(this," You haven't shipped anything");
                  return;
           }
                 
           
           while(rs.next()){
            src=src+"order_id: "+rs.getInt(1)+" lod "+rs.getDouble(2)+" shipid: "+rs.getInt(3)+"\n";
           }
           jL8.setVisible(true);
        jTF4.setVisible(true);
        jB11.setVisible(true);
        if(ct==0){
           JOptionPane.showMessageDialog(this,src);
            ct=1;
        }
          
        }
        catch(Exception e){
             System.out.print("In entp_log.java.... "+e.getLocalizedMessage());
        }
            
        
        
        
    }//GEN-LAST:event_jB9ActionPerformed

    private void jB10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB10ActionPerformed
        // TODO add your handling code here:
        
        if(jTF3.getText().length()==0)
        {
          JOptionPane.showMessageDialog(this,"Please enter a valid ship id");
          return;
        }
        int shipid=Integer.parseInt(jTF3.getText());
        try{
            con=DriverManager.getConnection(url, user, password);
	   st=con.createStatement();
           ResultSet rs;
           int max;
        rs=st.executeQuery("select * from Ship where id="+shipid);
        rs.next();
        max=rs.getInt(4);
			
			
	if(lod>max)
	System.out.print("Overflow....");
	else
	{
          int costpm;
	costpm=rs.getInt(8);
	System.out.println("The total cost will be "+costpm*lod+"$");
        JOptionPane.showMessageDialog(this,"The total cost will be "+costpm*lod+"$");
        System.out.println(shipid);
        st.executeUpdate("update Status set weight=weight +"+lod+","+" destn="+ctr2+" where id="+shipid);
	System.out.println("Status updated");			
	st.executeUpdate("insert into serv(cust_id,ship_id,dep,arr,lod) values("+id+","+shipid+","+null+","+null+","+lod+")");
	DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
	Calendar cal = Calendar.getInstance();
	cal.add(Calendar.DATE, 25);
	JOptionPane.showMessageDialog(this,"Your order has been placed... tentative departure: "+dateFormat.format(cal.getTime()));
	}
        
        st.close();
        con.close();
        }
        catch(Exception e){
       System.out.println("In entp_log.java...."+e.getLocalizedMessage());
       }
        
    }//GEN-LAST:event_jB10ActionPerformed

    private void jB11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB11ActionPerformed
        // TODO add your handling code here:
        
        try{
          con=DriverManager.getConnection(url, user, password);
		  st=con.createStatement();
		  int shipid;
		  float lod;
int order_id=Integer.parseInt(jTF4.getText());

                  // display all the orders of customer and then read order_id and delete thta one  
		  ResultSet rs=st.executeQuery("select ship_id,lod from serv where cust_id= "+id +" and order_id="+order_id);
		  
		  if(rs .next()==false)
			   JOptionPane.showMessageDialog(this,"You haven't shipped anything yet...");
		  else
		  {
			  
	          shipid=rs.getInt(1);
		  lod=rs.getFloat(2);
		  rs=st.executeQuery("select * from Status where id="+shipid);
		  rs.next();
		  if(rs.getBoolean(2))
			  JOptionPane.showMessageDialog(this,"ship is engaged, order can't be cancelled");
		  else {
			  
			  st.executeUpdate("update Status set weight=weight -"+lod+" where id="+shipid);
			  rs=st.executeQuery("select weight from Status where id="+shipid);
			  rs.next();
			  lod=rs.getFloat(1);
			  if((int)lod==0) {     // casting in case if precisions differ in tables
				  st.executeUpdate("update Status set destn="+null+" where id="+shipid);
				  
				  
			  }
			  st.executeUpdate("delete from serv where order_id="+order_id);
                           JOptionPane.showMessageDialog(this,"Successfully deleted order");
		  }
		  }  
        }
        catch(Exception e){
       System.out.println("In entp_log.java...."+e.getLocalizedMessage());
       }
    }//GEN-LAST:event_jB11ActionPerformed

    private void scbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scbActionPerformed
        // TODO add your handling code here:
        splash sc=new splash();
        sc.setVisible(true);
        setVisible(false);
        
        
    }//GEN-LAST:event_scbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(entp_log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(entp_log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(entp_log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(entp_log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new entp_log().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JComboBox<String> cb1;
    private javax.swing.JComboBox<String> cb2;
    private javax.swing.JButton jB10;
    private javax.swing.JButton jB11;
    private javax.swing.JButton jB4;
    private javax.swing.JButton jB5;
    private javax.swing.JButton jB6;
    private javax.swing.JButton jB7;
    private javax.swing.JButton jB8;
    private javax.swing.JButton jB9;
    private javax.swing.JComboBox<String> jCB3;
    private javax.swing.JComboBox<String> jCB4;
    private javax.swing.JLabel jL3;
    private javax.swing.JLabel jL4;
    private javax.swing.JLabel jL7;
    private javax.swing.JLabel jL8;
    private javax.swing.JLabel jL9;
    private javax.swing.JTextField jTF1;
    private javax.swing.JTextField jTF3;
    private javax.swing.JTextField jTF4;
    private javax.swing.JButton jb2;
    private javax.swing.JLabel jl1;
    private javax.swing.JLabel jl2;
    private javax.swing.JButton scb;
    // End of variables declaration//GEN-END:variables
}
