/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fre;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author gaurav
 */
public class ship_log extends javax.swing.JFrame {

    /**
     * Creates new form ship_log
     */
    int id,type,destn;
    String name;
     Statement st;
    Connection con;
    String url,user,password;
    public ship_log() {
        initComponents();
        try{
          url="jdbc:mysql://localhost:3306/dbproject?autoReconnect=true&useSSL=false";
	  user="root";
	  password="tiger";
			
	Class.forName("com.mysql.jdbc.Driver");
				
		}
		catch(Exception e){
			System.out.println("Exception in connecting...."+e.getLocalizedMessage());
		}
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        scb = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jL1 = new javax.swing.JLabel();
        bx1 = new javax.swing.JCheckBox();
        jL2 = new javax.swing.JLabel();
        bx2 = new javax.swing.JCheckBox();
        jL3 = new javax.swing.JLabel();
        bx3 = new javax.swing.JCheckBox();
        jL4 = new javax.swing.JLabel();
        bx4 = new javax.swing.JCheckBox();
        jL5 = new javax.swing.JLabel();
        bx5 = new javax.swing.JCheckBox();
        jL6 = new javax.swing.JLabel();
        bx6 = new javax.swing.JCheckBox();
        jl7 = new javax.swing.JLabel();
        bx7 = new javax.swing.JCheckBox();
        jB2 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jL8 = new javax.swing.JLabel();
        jB3 = new javax.swing.JButton();
        jL9 = new javax.swing.JLabel();
        jTF1 = new javax.swing.JTextField();
        jB4 = new javax.swing.JButton();
        jL10 = new javax.swing.JLabel();
        jTF2 = new javax.swing.JTextField();
        jL11 = new javax.swing.JLabel();
        jTF3 = new javax.swing.JTextField();
        jL12 = new javax.swing.JLabel();
        jTF4 = new javax.swing.JTextField();
        jB5 = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        scb.setText("sign_out");
        scb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scbActionPerformed(evt);
            }
        });

        jButton1.setText("Update maintenance");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jL1.setText("Anchor: ");

        jL2.setText("Bow: ");

        jL3.setText("Cabin: ");

        jL4.setText("Scope: ");

        jL5.setText("Funnel: ");

        jL6.setText("Stern: ");

        jl7.setText("Propeller: ");

        jB2.setText("OK");
        jB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB2ActionPerformed(evt);
            }
        });

        jButton2.setText("Current Status");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jB3.setText("Engage");
        jB3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB3ActionPerformed(evt);
            }
        });

        jL9.setText("Set  Departure Date(yyyy-mm-dd): ");

        jB4.setText("Update Location");
        jB4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB4ActionPerformed(evt);
            }
        });

        jL10.setText("Name or some landmark: ");

        jTF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF2ActionPerformed(evt);
            }
        });

        jL11.setText("Latitude:");

        jL12.setText("Longitude:");

        jB5.setText("End of journey");
        jB5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jB3)
                .addGap(169, 169, 169))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(scb)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jL1)
                            .addComponent(jL2)
                            .addComponent(jL3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bx1)
                            .addComponent(bx3)
                            .addComponent(bx2))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jL4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jL5)
                                    .addComponent(jL6))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bx5)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(bx6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bx4)
                                        .addGap(52, 52, 52)
                                        .addComponent(jl7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bx7)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jB2)
                                .addGap(196, 196, 196))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jL11)
                            .addComponent(jL10)
                            .addComponent(jL12))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 244, Short.MAX_VALUE)
                                .addComponent(jB4)
                                .addGap(123, 123, 123))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTF2, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                                    .addComponent(jTF3)
                                    .addComponent(jTF4))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jL8, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jL9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTF1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jB5))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(scb))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jButton1)))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jL1)
                                    .addComponent(bx1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jL2))
                            .addComponent(bx2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jL4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jL5))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(bx4)
                                .addComponent(jl7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bx7)
                                .addGap(7, 7, 7)))
                        .addGap(5, 5, 5)
                        .addComponent(bx5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jL3)
                        .addComponent(bx3)
                        .addComponent(jL6)
                        .addComponent(bx6))
                    .addComponent(jB2))
                .addGap(51, 51, 51)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jL8, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jL9)
                    .addComponent(jTF1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jB3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jB5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jL10)
                    .addComponent(jTF2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTF4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jL12))
                .addGap(11, 11, 11)
                .addComponent(jB4))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        jL1.setVisible(false);
        jL2.setVisible(false);
        jL3.setVisible(false);
        jL4.setVisible(false);
        jL5.setVisible(false);
        jL6.setVisible(false);
        jL8.setVisible(false);
        jl7.setVisible(false);
        
        bx1.setVisible(false);
        bx2.setVisible(false);
        bx3.setVisible(false);
        bx4.setVisible(false);
        bx5.setVisible(false);
        bx6.setVisible(false);
        bx7.setVisible(false);
        jB2.setVisible(false);
        
        jL9.setVisible(false);
        jTF1.setVisible(false);
        jB3.setVisible(false);
        
        jB5.setVisible(false);
        
        jTF2.setVisible(false);
        jTF3.setVisible(false);
        jTF4.setVisible(false);
        
        jL10.setVisible(false);
        jL11.setVisible(false);
        jL12.setVisible(false);
        jB4.setVisible(false);
    }//GEN-LAST:event_formWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jL1.setVisible(true);
        jL2.setVisible(true);
        jL3.setVisible(true);
        jL4.setVisible(true);
        jL5.setVisible(true);
        jL6.setVisible(true);
        jl7.setVisible(true);
       jB2.setVisible(true);
        bx1.setVisible(true);
        bx2.setVisible(true);
bx3.setVisible(true);
bx4.setVisible(true);
bx5.setVisible(true);
bx6.setVisible(true);
bx7.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB2ActionPerformed
        // TODO add your handling code here:
        int val[]=new int[7];
        
        for(int i=0;i<7;i++)
            val[i]=0;
        
        if(bx1.isSelected())
            val[0]=1;
        if(bx2.isSelected())
            val[1]=1;
        if(bx3.isSelected())
            val[2]=1;
        if(bx4.isSelected())
            val[3]=1;
        if(bx5.isSelected())
            val[4]=1;
        if(bx6.isSelected())
            val[5]=1;
        if(bx7.isSelected())
            val[6]=1;
        
     try{
         con=DriverManager.getConnection(url, user, password);
        st=con.createStatement();
        ResultSet rs;
        st.executeUpdate("update Maintenance set anchor="+val[0]+",bow="+val[1]+
                ",cabin="+val[2]+",scope="+val[3]+",funnel="+
                val[4]+",stern="+val[5]+",propeller="+val[6]+" where id="+id);
        	int sum=0; 
            
         for(int x=2;x<=5;x++)
     	   {
     		   sum=sum+val[x];
     	   }
     	   
     	   if(sum==0)
     	   {
     		   sum=0;
     	   }
     	   else
     	   {
     		   sum=1;
     	   }
        	
        	st.executeUpdate("update Status set Maintenance="+sum+" where id="+id);
                 JOptionPane.showMessageDialog(this,"Updated");
     }
     catch(Exception e){
       System.out.println("In ship_log.java -"+e.getLocalizedMessage());
     }
    }//GEN-LAST:event_jB2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            jL8.setVisible(true);
          con=DriverManager.getConnection(url, user, password);
        st=con.createStatement();
        ResultSet rs;
        float lod;
        boolean engaged;
       
       
        rs=st.executeQuery("select engaged,weight,destn from Status where id="+id);
        rs.next();
        engaged=rs.getBoolean(1);
        lod=rs.getFloat(2);
        destn=rs.getInt(3);
        
        rs=st.executeQuery("select min from Ship where id="+id);
        rs.next();
        if(lod> rs.getInt(1)){
        	
        	if(!engaged) {
        	
                  jL8.setText("Ready to engage captain???");
                  jL9.setVisible(true);
                  jTF1.setVisible(true);
                  jB3.setVisible(true);
            	
          	}
        	else if(engaged) {
        	
                    String dtn="";    
                    if(destn==1)
                       dtn="INDIA";
                    if(destn==2)
                       dtn="SOUTH AFRICA";
                    if(destn==3)
                       dtn="DUBAI";
                    if(destn==4)
                       dtn="CANADA";
                    if(destn==5)
                       dtn="SPAIN";
                    
                    jL8.setText(name+ " is engaged, enroute to "+dtn);
                    jTF2.setVisible(true);
        jTF3.setVisible(true);
        jTF4.setVisible(true);
        jB5.setVisible(true);
        jL10.setVisible(true);
        jL11.setVisible(true);
        jL12.setVisible(true);
        jB4.setVisible(true);
        }
        	
        }
        else{
        	jL8.setText("Still needs more load, can't be engaged");
        }
		
        st.close();
        con.close();  
            
        }
      catch(Exception e){
       System.out.println("In ship_log.java -"+e.getLocalizedMessage());
     }  
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jB3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB3ActionPerformed
        // TODO add your handling code here:
        try{
        con=DriverManager.getConnection(url, user, password);
        st=con.createStatement();
        ResultSet rs;
        
        st.executeUpdate("update Status set engaged="+true+" where id="+id);
            		
        st.executeUpdate("update serv set dep="+"'"+jTF1.getText()+
                                "'"+" where ship_id="+id);
        
        JOptionPane.showMessageDialog(this,"Daparture date set");
        }
      catch(Exception e){
       System.out.println("In ship_log.java -"+e.getLocalizedMessage());
     }  
    }//GEN-LAST:event_jB3ActionPerformed

    private void jTF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF2ActionPerformed

    private void jB4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB4ActionPerformed
        // TODO add your handling code here:
        
        try{
           float lat,logt;
        con=DriverManager.getConnection(url, user, password);
        st=con.createStatement();
        ResultSet rs;
        lat=(float)Double.parseDouble(jTF3.getText());
        logt=(float)Double.parseDouble(jTF4.getText());
        st.executeUpdate("insert into uploc(ship_id,name,lat,logt) values("+
                id+","+"'"+jTF2.getText()+"'"+","+lat+","+logt+")");
	st.executeUpdate("call up_dt_time("+id+")"); 
        JOptionPane.showMessageDialog(this,"Location updated");
        }
      catch(Exception e){
       System.out.println("In ship_log.java -"+e.getLocalizedMessage());
     }  
    }//GEN-LAST:event_jB4ActionPerformed

    private void scbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scbActionPerformed
        // TODO add your handling code here:
        splash s=new splash();
        s.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_scbActionPerformed

    private void jB5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB5ActionPerformed
        // TODO add your handling code here:
        
        try{
        con=DriverManager.getConnection(url, user, password);
        st=con.createStatement();
        ResultSet rs;
         String dtn="";    
                    if(destn==1)
                       dtn="INDIA";
                    if(destn==2)
                       dtn="SOUTH AFRICA";
                    if(destn==3)
                       dtn="DUBAI";
                    if(destn==4)
                       dtn="CANADA";
                    if(destn==5)
                       dtn="SPAIN";
         st.executeUpdate("insert into uploc(ship_id,name,lat,logt) values("+
                id+","+"'"+dtn+"'"+","+null+","+null+")");
	st.executeUpdate("call up_dt_time("+id+")");
        
        
        rs=st.executeQuery("select cust_id from serv where ship_id="+id);
        rs.next();
        int cust_id=rs.getInt(1);
        st.executeUpdate("update serv set arr=curdate() where cust_id="+cust_id);
       st.executeUpdate("update Ship set ctr="+destn+" where id="+id);
       st.executeUpdate("update Status set destn="+null+" ,weight=0.0,engaged=0 where id="+id);
       
       JOptionPane.showMessageDialog(this,name+"'s journey ends near "+dtn);
        }
      catch(Exception e){
       System.out.println("In ship_log.java -"+e.getLocalizedMessage());
     }  
    }//GEN-LAST:event_jB5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ship_log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ship_log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ship_log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ship_log.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ship_log().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox bx1;
    private javax.swing.JCheckBox bx2;
    private javax.swing.JCheckBox bx3;
    private javax.swing.JCheckBox bx4;
    private javax.swing.JCheckBox bx5;
    private javax.swing.JCheckBox bx6;
    private javax.swing.JCheckBox bx7;
    private javax.swing.JButton jB2;
    private javax.swing.JButton jB3;
    private javax.swing.JButton jB4;
    private javax.swing.JButton jB5;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jL1;
    private javax.swing.JLabel jL10;
    private javax.swing.JLabel jL11;
    private javax.swing.JLabel jL12;
    private javax.swing.JLabel jL2;
    private javax.swing.JLabel jL3;
    private javax.swing.JLabel jL4;
    private javax.swing.JLabel jL5;
    private javax.swing.JLabel jL6;
    private javax.swing.JLabel jL8;
    private javax.swing.JLabel jL9;
    private javax.swing.JTextField jTF1;
    private javax.swing.JTextField jTF2;
    private javax.swing.JTextField jTF3;
    private javax.swing.JTextField jTF4;
    private javax.swing.JLabel jl7;
    private javax.swing.JButton scb;
    // End of variables declaration//GEN-END:variables
}
